"""empty message

Revision ID: 03ab34a6bb86
Revises: bef8db609cee
Create Date: 2020-11-14 20:33:18.200931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ab34a6bb86'
down_revision = 'bef8db609cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Order', 'Client', ['client_id'], ['id'])
    op.create_foreign_key(None, 'Order', 'Product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    # ### end Alembic commands ###
