"""empty message

Revision ID: 2c14e19c2f92
Revises: 7e6fd10c2282
Create Date: 2020-11-15 17:22:39.587486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c14e19c2f92'
down_revision = '7e6fd10c2282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Order', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('Order', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('Product', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('Product', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Product', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('Product', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('Order', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('Order', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
