"""empty message

Revision ID: 56f4f346442a
Revises: 2c14e19c2f92
Create Date: 2020-11-15 18:18:26.657553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f4f346442a'
down_revision = '2c14e19c2f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('order_value', table_name='Order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('order_value', 'Order', ['order_value'], unique=True)
    # ### end Alembic commands ###
