"""empty message

Revision ID: 769d5875a08b
Revises: c18f55180c2d
Create Date: 2020-11-23 12:57:26.648078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '769d5875a08b'
down_revision = 'c18f55180c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Order', 'order_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Order', 'order_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
