"""empty message

Revision ID: 7e6fd10c2282
Revises: 03ab34a6bb86
Create Date: 2020-11-15 12:24:49.034285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e6fd10c2282'
down_revision = '03ab34a6bb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Client', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('Client', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index('password', table_name='Client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'Client', ['password'], unique=True)
    op.alter_column('Client', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('Client', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
